# Copyright (C) 2020  Matthew Glazar
# See end of file for extended copyright information.

name: tag build
on: push

jobs:
  tag-build:
    name: tag
    runs-on: ubuntu-latest
    container: ghcr.io/quick-lint/quick-lint-js-github-clang-format:v1
    steps:
      - name: create tag file
        run: |
          printf 'Git-Commit: %s\nWebsite-URL: %s' ${{ github.sha }} 'https://quick-lint-js.com/' >README
      - name: upload tag file
        if: ${{ github.repository_owner == 'quick-lint' }}
        uses: quick-lint/sftp-upload@1fa54164d4bdd081207a6e54ec143d8dda3a7fb8 # v3
        with:
          host: ${{ secrets.artifacts_host }}
          local-file-globs: README
          private-key: ${{ secrets.artifacts_key }}
          remote-directory: ${{ secrets.artifacts_root }}/builds/${{ github.sha }}/
          user: ${{ secrets.artifacts_user }}

      - name: checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      # HACK(strager): Work around the following error from 'git ls-files' used
      # by ./tools/format:
      #
      #     fatal: unsafe repository ('/__w/quick-lint-js/quick-lint-js' is owned by someone else)
      #
      # See also: https://github.com/actions/checkout/issues/760
      - name: work around permission issue
        run: git config --global --add safe.directory /__w/quick-lint-js/quick-lint-js

      - name: get version
        id: getversion
        run: printf 'QLJS_VERSION=%s\n' "$(head -n1 version)" >>"${GITHUB_OUTPUT}"
        shell: bash

      - name: create source archive
        run: git archive --format tar.gz --prefix "quick-lint-js-${QLJS_VERSION}/" --output "quick-lint-js-${QLJS_VERSION}.tar.gz" HEAD
        env:
          QLJS_VERSION: ${{ steps.getversion.outputs.QLJS_VERSION }}
      - name: upload source archive
        if: ${{ github.repository_owner == 'quick-lint' }}
        uses: quick-lint/sftp-upload@1fa54164d4bdd081207a6e54ec143d8dda3a7fb8 # v3
        with:
          host: ${{ secrets.artifacts_host }}
          local-file-globs: quick-lint-js-${{ steps.getversion.outputs.QLJS_VERSION }}.tar.gz
          private-key: ${{ secrets.artifacts_key }}
          remote-directory: ${{ secrets.artifacts_root }}/builds/${{ github.sha }}/source/
          user: ${{ secrets.artifacts_user }}

# quick-lint-js finds bugs in JavaScript programs.
# Copyright (C) 2020  Matthew Glazar
#
# This file is part of quick-lint-js.
#
# quick-lint-js is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# quick-lint-js is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with quick-lint-js.  If not, see <https://www.gnu.org/licenses/>.
